services:
  dev-env:
    build:
      dockerfile: Dockerfile.devEnv
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - .git:/usr/src/app/.git:ro # for jest watch

  lambda-dev:
    build:
      dockerfile: Dockerfile.devLambda
      args:
        - TS_COMPILER_DEV=${TS_COMPILER_DEV}
    env_file:
      - .env
    volumes:
      - ./:/var/task
    ports:
      - "3000:8080"