# Description: 
# Dockerfile for local development of lambda functions.
# this is handling typescript compilation and running the lambda function via @swc-node/register and a given bootstrap.js file

FROM public.ecr.aws/lambda/nodejs:20
WORKDIR ${LAMBDA_TASK_ROOT}
COPY . .
# RUN npm install -g typescript ts-node
ENV NODE_OPTIONS="-r @swc-node/register"
COPY bootstrap.js /var/runtime/bootstrap.js
CMD ["bootstrap.handler"]